PREFIX any23: <http://vocab.sindice.net/any23#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX unit: <https://unit.no/ontology#>

CONSTRUCT {
  ?uri unit:entityDescription ?entityDescription .
  ?entityDescription a unit:EntityDescription ;
        unit:mainTitle ?title ;
        unit:tag ?subject ;
        unit:description ?description ;
        unit:contributor ?contributor .
  ?contributor a unit:Contributor ;
        unit:identity ?identity .
  ?identity a unit:Idendity ;
        unit:name ?creator .
} WHERE {
  # title
  OPTIONAL { ?uri any23:dc.title ?title }
  OPTIONAL { ?uri any23:citation_title ?title }
  # creator
  OPTIONAL { ?uri any23:dc.creator ?creator }
  OPTIONAL { ?uri any23:citation_author ?creator }
  # subject
  OPTIONAL { ?uri any23:dc.subject ?subject }
  # date
  OPTIONAL { ?uri any23:dc.date ?date }
  # description
  OPTIONAL { ?uri any23:dc.description ?description }
  # language
  OPTIONAL { ?uri any23:dc.language ?language }
}