PREFIX any23: <http://vocab.sindice.net/any23#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX unit: <https://unit.no/ontology#>

CONSTRUCT {
  <__URI__> a unit:PublicationRequest ;
    unit:entityDescription ?entityNode .
  ?entityNode a unit:EntityDescription ;
    unit:mainTitle ?mainTitle ;
    unit:description ?description ;
    unit:tag ?tag ;
    unit:contributor ?contributorNode .
  ?contributorNode a unit:Contributor ;
    unit:identity ?identityNode .
  ?identityNode a unit:Identity ;
    unit:name ?name .
} WHERE {
  select DISTINCT (STR(?title) AS ?mainTitle)
                  ?entityNode
                  ?contributorNode
                  ?identityNode
                  (STR(?creator) AS ?name)
                  (STR(?subject) AS ?tag)
                  (STR(?rawDate) AS ?date)
                  (STR(?rawDescription) AS ?description)
                  (STR(?rawLanguage) AS ?language) {
    BIND (BNODE() AS ?entityNode)

    {
      <__URI__> any23:dc.title ?title
    }
    UNION {
      <__URI__> any23:dc.creator ?creator
      BIND(BNODE() AS ?contributorNode)
      BIND(BNODE() AS ?identityNode)
      FILTER (BOUND(?creator) && strlen(?creator)>0)
    }
    UNION {
      <__URI__> any23:dc.subject ?subject
    }
    UNION {
      <__URI__> any23:dc.date ?rawDate
    }
    UNION {
      <__URI__> any23:dc.description ?rawDescription
    }
    UNION {
      <__URI__> any23:dc.language ?rawLanguage
    }
  }
}