plugins {
    id 'nva.java-conventions'
}

nva {
    errorprone {
        allErrorsAsWarnings = true // FIXME
    }
    pmd {
        rulesetFile = rootProject.file('config/pmd/ruleset.xml')
    }
    spotless {
        enabled = false // FIXME
    }
}

dependencies {
    testImplementation libs.bundles.testing
}
