plugins{
    id 'jacoco-report-aggregation'
    id 'base'
    id 'java-library'
    id 'io.github.michael-nestler.spectral'
}


repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    subprojects.forEach {
        jacocoAggregation it
    }
}


tasks.named('check') {
    dependsOn tasks.named('spectral')
}

spectral {
    documents.from("docs/*.yaml")
    ruleset.set(file('.spectral.yaml'))
}
