plugins {
    id 'nva.fetch.doi.java-conventions'
}

dependencies {
    api(nvaCatalog.jackson.annotations)
    api(nvaLibs.apigateway)
    api(nvaLibs.identifiers)
    implementation(nvaLibs.core)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.jackson.databind)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaLibs.json)
    testImplementation(project(":json-config"))
}
