plugins {
    id 'nva.fetch.doi.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.apigateway)
    api(nvaLibs.clients)
    api(nvaLibs.core)
    api(project(":doi-proxy"))
    api(project(":doi-transformer"))
    api(project(":fetch-doi-commons"))
    api(project(":metadata-transformer"))
    implementation(nvaCatalog.httpcore5)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.identifiers)
    implementation(nvaLibs.json)
    implementation(project(":json-config"))
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.zalando)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
}

test{
    environment("API_HOST", "api.localhost.nva.aws.unit.no")
    environment("ALLOWED_ORIGIN", "*")
    environment("COGNITO_AUTHORIZER_URLS", "http://localhost:3000")
    environment("PUBLICATION_API_HOST", "localhost")
}
