plugins {
    id 'nva.fetch.doi.java-conventions'
}

dependencies {
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.core)
    api(nvaLibs.apigateway)
    api(nvaLibs.doi)
    api(project(":fetch-doi-commons"))
    implementation(nvaCatalog.commons.validator)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.core)
    implementation(project(":json-config"))
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.jackson.databind)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaLibs.json)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
}
