plugins {
    id 'nva.fetch.doi.java-conventions'
}

dependencies {
    api(libs.apache.any23.api) {
        exclude group: 'org.yaml', module: 'snakeyaml'
        exclude group: 'org.apache.logging.log4j', module: 'log4j-slf4j-impl'
    }
    api(libs.rdf4j.model.api)
    api(project(":fetch-doi-commons"))
    implementation(libs.apache.any23.core) {
        exclude group: 'org.yaml', module: 'snakeyaml'
        exclude group: 'org.apache.logging.log4j', module: 'log4j-slf4j-impl'
    }
    implementation(libs.rdf4j.model)
    implementation(libs.rdf4j.repository.api)
    implementation(libs.rdf4j.repository.sail)
    implementation(libs.rdf4j.sail.api)
    implementation(libs.rdf4j.sail.memory)
    implementation(nvaCatalog.commons.validator)
    implementation(nvaCatalog.httpcore5)
    implementation(nvaCatalog.jackson.databind)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.apigateway)
    implementation(nvaLibs.core)
    implementation(project(":json-config"))
    runtimeOnly(libs.rdf4j.rio.api)
    testImplementation(libs.j2html)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.wiremock.core)
    testImplementation(nvaLibs.json)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
}

test {
    environment "API_HOST", "api.localhost.nva.aws.unit.no"
}
